### ISSUE TITLE
Remaining work

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/nitro-espresso-integration#129]
Remaining work:
- [x] Fix validation (fetching VidCommon - endpoint for fetching, update go client), getting CI to pass on this PR - @ImJeremyHe @nomaxg 
- [x] module root in dockerfile @nomaxg 
- [x] add fraud proof section @nomaxg 
- [x] fix fraud proofs - update hotshot contracts @ImJeremyHe

**Comment by sveitser** [comment]
@ImJeremyHe @nomaxg what's the status on this?

**Comment by ImJeremyHe** [comment]
@sveitser These are done.
