### ISSUE TITLE
Contract: Upgrade the light client contract address

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/nitro-espresso-integration#135]
Currently we pass our light client contract address into the rollup contract when initializing it. We need to utilize nitro's upgrade tools to upgrade our contract address

https://github.com/EspressoSystems/nitro-espresso-integration/blob/38f7811d2b408f5d8c8bb09256f22a7b5a398297/deploy/deploy.go#L143

**Comment by sveitser** [comment]
@ImJeremyHe are you sure about this? I think the HostIO contract is not upgradable and that therefore it's fine to use the constructor.

**Comment by ImJeremyHe** [comment]
@sveitser Thanks for confirming that. I am not so familiar with this. Just created this issue when I thought of it. I will just close this issue.
