### ISSUE TITLE
Create a fast finality / Espresso pre-confirmations full node

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/nitro-espresso-integration#195]
Rationale: Instead of connecting to a Nitro validator Ethereum RPC a bridge can connect to this node to reach faster finality.

### Requirements
- Receive finalized messages via Espresso block namespace from Espresso query service
- Build L2 block from finalized Espresso finalized messages
- Expose Ethereum RPC (like existing nitro sequencer or validator node)

### Stretch goal
- Correct handling of re-orgs. For the first prototype we can defer this unless it's straightforward.

### Not requirements
- Forward transactions to the Nitro sequencer. If we can get this for free that's fine but we don't need it.

**Comment by sveitser** [comment]
Closed in favor of #235
