### ISSUE TITLE
Sovereign Sequencer: Escape Hatch

### ISSUE THREAD

**Issue by Sneh1999** [EspressoSystems/nitro-espresso-integration#221]
**Is your feature request related to a problem? Please describe.**
Current sovereign sequencer design doesn't contain any escape hatch. As a reason, if hotshot is down, batch poster will not post any batch to L1 because of [this](https://github.com/EspressoSystems/nitro-espresso-integration/blob/9f4ef0d81db571793ce92d9360d64d491aa347cc/arbnode/batch_poster.go#L1306)  code. We will need to re-think how we can implement an escape hatch for sovereign sequencer design

**Additional context**
More details about escape hatch's current implementation is [here](https://www.notion.so/espressosys/Arbitrum-Centralized-Sequencer-Escape-Hatch-Implementation-Plan-fba46757aa8f4a3eb9118012744f32b2?pvs=4)

**Comment by ImJeremyHe** [comment]
I think we can adopt the same strategy to implement a new escape hatch:
- Run a thread to monitor the liveness of HotShot in the batch poster
- If the HotShot is down/up, the batch poster should disable/enable the function of sending messages to HotShot for fast finality
- The data posted by batch poster should contain the HotShot liveness info and the Sequencer Inbox Contract should have the ability to check the HotShot liveness. The Sequencer Inbox Contract will do the espresso validation when the HotShot is live

**Comment by sveitser** [comment]
@ImJeremyHe validation in the sequencer inbox contract is currently in planning phase. This issue is about having an escape hatch for the sovereign sequencer (which is what we have currently implemented). Apart from that I agree that we should do what you described if we implement validation in the smart contract.

**Comment by sveitser** [comment]
@zacshowa These changes are quite similar to the escape hatch we used to have so it may be beneficial to look at the code we recently removed instead of doing it all from scratch.

**Comment by zacshowa** [comment]
One question I currently have surrounding this work is if we need the transaction streamer to be calling its [`executeMessages`](https://github.com/EspressoSystems/nitro-espresso-integration/blob/8d4bc6c51728363cc2b0c1c851b0ddb63c3f0173/arbnode/transaction_streamer.go#L1533) function when the escape hatch is set to allow the centralized sequencer to take back over.
It seems like this is important in feeding messages to the broadcast server. However, I don't know precisely what the broadcast server does with respect to the sovereign sequencer. 

Regardless I think some escape hatch logic needs to live in the `transaction_streamer` as well as the `batch_poster` to switch between their respective behaviors. Currently the logic that submits transactions to espresso lives in the [`transaction_streamer.`](https://github.com/EspressoSystems/nitro-espresso-integration/blob/8d4bc6c51728363cc2b0c1c851b0ddb63c3f0173/arbnode/transaction_streamer.go#L1482) However, my current work on this issue [(here)](https://github.com/EspressoSystems/nitro-espresso-integration/pull/242) has the hotshot monitor live in the batch poster and not share its boolean pointer with the transaction streamer. This leaves us with a couple options to implement a single listener that updates the disparate components. 

One approach would be to add a setter method onto the `transaction_streamer` that allows us to toggle an `escapeHatchOpen` boolean. This method could be called from the `batch_poster` whenever the `HotShotMonitor` toggles the escape hatch boolean in the `batch_poster`.

Another approach would be to have the `escapeHatchOpen` a boolean reference be shared by the `batch_poster` and `transaction_streamer`.  using this approach would toggle the escape hatch in both places simultaneously. My worry with this approach is that multiple components would then regularly be attempting to lock the mutex. This could lead to excessive blocking on this mutex and introduce some latency. The main source of this latency would be the amount of time the `HotShotMonitor` has to wait for queries to the light client.
