### ISSUE TITLE
Update e2e test to include stakers

### ISSUE THREAD

**Issue by Sneh1999** [EspressoSystems/nitro-espresso-integration#225]
**Is your feature request related to a problem? Please describe.**
Update espresso e2e tests to include stakers. Test that when a faulty staker stakes on an incorrect `HOTSHOT_COMMITMENT` the challenge ends up in `ERROR_HOTSHOT_COMMITMENT` and the faulty staker losses the challenge

**Additional context**
Update the given file: https://github.com/EspressoSystems/nitro-espresso-integration/blob/integration/system_tests/espresso_e2e_test.go with this test

**Comment by sveitser** [comment]
Will probably not be needing this for currently preferred solutions.
