### ISSUE TITLE
E2E Tests: Add tests for batch poster with Espresso validation

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/nitro-espresso-integration#299]
New tests we probably want to add. Feel free to add more.

- [ ] E2E: Happy path of correct validation (as much as that's possible, given that it won't be easy to run in a TEE environment)
- [ ] Unhappy path with incorrect TEE signature (this can also be moved to a separate test if easier)

The e2e flow should work for celestia branch and our integration branch

**Comment by Sneh1999** [comment]
https://github.com/EspressoSystems/nitro-testnode/pull/68
