### ISSUE TITLE
Test functionality of nitro node with Espresso Integration

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/nitro-espresso-integration#35]
- [x] transfer on L2
 ```
cast balance 0x673C9b46952080D3bf1B8d689C7BBC590a8755Cb --rpc-url http://localhost:8547
./test-node.bash script send-l2 --to address_0x673C9b46952080D3bf1B8d689C7BBC590a8755Cb --ethamount 5
cast balance 0x673C9b46952080D3bf1B8d689C7BBC590a8755Cb --rpc-url http://localhost:8547
```
- [x] bridge deposit from L1
```
cast balance 0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E --rpc-url http://localhost:8547
./test-node.bash script bridge-funds --ethamount 1 --wait
cast balance 0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E --rpc-url http://localhost:8547
```
- [ ] withdrawal to L1: ? not sure how to test
- [x] block explorer: 
```
./testnode.bash --init --dev --espresso --validate --blockscout
```
  + Go to http://localhost:4000
- [stretch] fraud proofs: no, this is currently not supported because we haven't looked into implementing the one step proving

**Comment by ImJeremyHe** [comment]
Maybe [here](https://github.com/EspressoSystems/arbitrum-sdk/blob/427084ceee4ee35d620477c8f2f9974e14647049/src/lib/assetBridger/ethBridger.ts#L290) is the place to withdraw to L1?

**Comment by sveitser** [comment]
I'm closing this since we've tested the most pressing functionality.
