### ISSUE TITLE
Validate that HotShot indices increase consecutively

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/nitro-espresso-integration#38]
We still need to ensure that batch hotshot numbers increase consecutively, without this, HotShot blocks can be censored.

**Comment by ImJeremyHe** [comment]
Would you mind explaning this further?
> HotShot blocks can be censored.

**Comment by nomaxg** [comment]
> Would you mind explaning this further?
> 
> > HotShot blocks can be censored.

Sure, if we don't do this index check, a sequencer could skip a hotshot block, excluding those transactions from the L2 chain altogether.
