### ISSUE TITLE
Compress empty blocks to reduce number of l2 blocks/save batch poster gas

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/nitro-espresso-integration#80]
Update the sequencer to batch empty blocks until some reasonable limit and submit a batch justification. We will need to modify the validation pipeline to validate batches of namespace proofs.

**Comment by jbearer** [comment]
If we're batching but not eliminating, maybe it would make sense to do this for all blocks?

**Comment by ImJeremyHe** [comment]
Is it possible for us not to store the proof into the message and just fetch the proof(like fetch the commitment) when validating?

**Comment by ImJeremyHe** [comment]
And maybe we can try to eliminate the empty block by these steps:
- not create any empty L2 block
- when validating a non-empty L2 block, suppose the hotshot height in the previous block is `h`, the current hotshot height is `p`. validators can fetch the jst from `h+1` to `p` to see if there is any non-empty block missing
- set a limit to prevent the validation input is too large for validating

**Comment by nomaxg** [comment]
We could fetch the proofs at validation time but I think a desired property is the ability to fully derive the validated the chain from L1 data. @jbearer is this still the case?

**Comment by jbearer** [comment]
yeah

**Comment by sveitser** [comment]
@ImJeremyHe We may be able to reduce the gas usage by configuring the batch poster interval.
