### ISSUE TITLE
Add the start hotshot block number into the L2 genesis block

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/nitro-espresso-integration#82]
Right now, `espresso-sequencer` fetches the latest espresso block as the start of building blocks.
https://github.com/EspressoSystems/nitro-espresso-integration/blob/c7db7e868bae14f363b4ebba354a2129d8edfc3a/execution/gethexec/espresso_sequencer.go#L63-L72

And the replay WASM allows any block height as the first start block.
https://github.com/EspressoSystems/nitro-espresso-integration/blob/c7db7e868bae14f363b4ebba354a2129d8edfc3a/cmd/replay/main.go#L305-L314

This means that the exact number of the start hotshot block is not deterministic and it can't be challenged.

Since the start hotshot block actually detemines the first non-genesis block of the L2, so it is appropriate to put it into the chain config.

**Comment by sveitser** [comment]
@ImJeremyHe to add details
