### ISSUE TITLE
Remove hardcoded namespace.rs library

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/nitro-espresso-integration#87]
Making espresso-sequencer wasm compatible would have been quite a lot of effort, and the sequencer repo wasn't compiling nicely in the test-node environment. For now, I did the very hacky thing of copying all VID verification code to its own [standalone module](https://github.com/EspressoSystems/nitro-espresso-integration/blob/update-espresso-go/arbitrator/vid-helper/src/namespace.rs). Long term we will need a better solution, I don't think that the sequencer repo is in a great state currently as an external dependency because of how coupled everything is. We should probably have all of the "pure" data structures in its own repo/module, ensuring that it can compile to wasm.

Update 2024-08-19:

There is currenly code in the nitro integration that is copied from Espresso sequencer because it wasn't possible to compile espresso-sequencer in the nitro environment. We have since then created a `types` crate in espresso sequencer that may or may not help with this. This issue can be closed if we have a way to no-longer include copied code from elsewhere into the nitro integration repo. We may have to create a separate crate that includes the espresso crypto that we can then use in the sequencer and in the nitro integration.

**Comment by sveitser** [comment]
We probably don't need this anymore if we move towards upfront validation of batches in L1.
