### ISSUE TITLE
Move hardcoded logic to compute txns commit to the Commit trait/espresso-go-sequencer

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/nitro-espresso-integration#88]
To validate that the namespace proof authenticates a set of transactions coming from Arbitrum, I check that the transaction hash of the txns returned by the proof equals the hash that the Arbitrum validation node passes down (computed upstream [here](https://github.com/EspressoSystems/nitro-espresso-integration/pull/86/files#diff-80bb4df2accf8199b202fe9745da4755ff7728b824901faafaa772e16014f032R14)). We should move this logic to commit/espresso-go-sequencer.

**Comment by sveitser** [comment]
@nomaxg we think we can close this, right?
